manifest:
  defaults:
    revision: v0.3
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/JaFettz
    - name: dactylmanuform
      url-base: https://github.com/JaFettz
    # Additional modules containing boards/shields/custom code can be listed here as well
    # See https://docs.zephyrproject.org/3.2.0/develop/west/manifest.html#projects
  projects:
    - name: zmk
      remote: zmkfirmware
      import: app/west.yml
    - name: zmk-dactly-manuform
      remote: dactylmanuform
      revision: main
  self:
    path: config
